[package]
name = "fc-sensu-syntax"
version = "0.1.0"
authors = ["Christian Kauhaus <kc@flyingcircus.io>"]
edition = "2018"
description = "Checks local sensu config for syntax and plausibility."

[profile.release]
panic = "abort"

[dependencies]
clap = "2.32"
failure = "0.1.5"
serde = "1"
serde_derive = "1"
serde_json = "1"
